{
  "openapi": "3.0.0",
  "info": {
    "title": "SmartConnections",
    "description": "This API have as it's objective the managemant of an user's contacts",
    "contact": { "email": "matheus.gualtieri56@gmail.com" },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000",
      "description": "API test"
    }
  ],
  "paths": {
    "/users": {
      "post": {
        "summary": "Register User",
        "description": "This route register a new user",
        "tags": ["Users"],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserCreate"
              },
              "example": {
                "email_login": "jojo@gmail.com",
                "full_name": "Jotaro Kujo",
                "password": "Dio",
                "emails": ["starplatinum@gmail.com"],
                "phone": [1010101010]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/UserResponse"
                }
              }
            }
          },
          "409": {
            "description": "Conflict",
            "content": {
              "aplication/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "User already exists"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid Body",
            "content": {
              "aplication/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": {
                      "full_name": ["Required"],
                      "email_login": ["Required"],
                      "emails": ["Required"],
                      "password": ["Required"],
                      "phone": ["Required"]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "summary": "Retrieve User",
        "description": "This route retrieve an user, needs authentication. Only the onwer can retrive it",
        "tags": ["Users"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "schema": {
              "type": "integer"
            },
            "required": true,
            "description": "Numeric ID of the user to get"
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "User not found"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "jwt must be provided"
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Insufficient permission"
                  }
                }
              }
            }
          }
        }
      },
      "patch": {
        "summary": "Update User",
        "description": "This route updates an user, needs authentication. Only the onwer can retrive it",
        "tags": ["Users"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "schema": {
              "type": "integer"
            },
            "required": true,
            "description": "Numeric ID of the user to get"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserResponse"
              },
              "examples": {
                "user": {
                  "value": {
                    "password": "ZaWordu"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/UserCreate"
                }
              }
            }
          },
          "400": {
            "description": "Invalid Body",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": {
                      "full_name": ["Required"],
                      "email_login": ["Required"],
                      "emails": ["Required"],
                      "password": ["Required"],
                      "phone": ["Required"]
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "User not found"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "jwt must be provided"
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Insufficient permission"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete User",
        "description": "This route deletes an user, needs authentication. Only the onwer can retrive it",
        "tags": ["Users"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "schema": {
              "type": "integer"
            },
            "required": true,
            "description": "Numeric ID of the user to get"
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "User not found"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "jwt must be provided"
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Insufficient permission"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/login": {
      "post": {
        "summary": "User Login",
        "description": "This route is used fot login",
        "tags": ["Login"],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Login"
              },
              "examples": {
                "user": {
                  "value": {
                    "email_login": "jojo@gmail.com",
                    "password": "Dio"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/UserResponse"
                }
              }
            }
          },
          "400": {
            "description": "Invalid Body",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": {
                      "email_login": ["Required"],
                      "password": ["Required"]
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Invalid credentials"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{id}/contacts": {
      "post": {
        "summary": "Create Contact",
        "description": "This route creates an contact for an user. Needs Authentication",
        "tags": ["Contacts"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "schema": {
              "type": "integer"
            },
            "required": true,
            "description": "Numeric ID of the user to get"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ContactRequest"
              },
              "examples": {
                "user": {
                  "value": {
                    "full_name": "Dio Brando",
                    "password": "JoJo",
                    "emails": ["ZaWordu@gmail.com", "vampire69@gmail.com"],
                    "phone": [1010101010]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Contact"
                }
              }
            }
          },
          "400": {
            "description": "Invalid Body",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": {
                      "full_name": ["Required"],
                      "emails": ["Required"],
                      "phone": ["Required"]
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "User not found"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "jwt must be provided"
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Insufficient permission"
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "summary": "List Contacts",
        "description": "This route lists contacts of an user, needs authentication. Only the onwer can list it",
        "tags": ["Contacts"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "schema": {
              "type": "integer"
            },
            "required": true,
            "description": "Numeric ID of the user to get"
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Contact"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "User not found"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "jwt must be provided"
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Insufficient permission"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{id}/contacts/{contactId}": {
      "patch": {
        "summary": "Update Contact",
        "description": "This route updates an contact, needs authentication. Only the onwer can retrive it",
        "tags": ["Contacts"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "schema": {
              "type": "integer"
            },
            "required": true,
            "description": "Numeric ID of the user to get"
          },
          {
            "in": "path",
            "name": "contactOd",
            "schema": {
              "type": "integer"
            },
            "required": true,
            "description": "Numeric ID of the contact to get"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ContactRequest"
              },
              "examples": {
                "user": {
                  "value": {
                    "full_name": "Za Wordu"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Contact"
                }
              }
            }
          },
          "400": {
            "description": "Invalid Body",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": {
                      "full_name": ["Required"],
                      "email_login": ["Required"],
                      "emails": ["Required"],
                      "password": ["Required"],
                      "phone": ["Required"]
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Contact not found"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "jwt must be provided"
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Insufficient permission"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete Contact",
        "description": "This route deletes an contact, needs authentication. Only the onwer can retrive it",
        "tags": ["Contacts"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "schema": {
              "type": "integer"
            },
            "required": true,
            "description": "Numeric ID of the user to get"
          },
          {
            "in": "path",
            "name": "contactOd",
            "schema": {
              "type": "integer"
            },
            "required": true,
            "description": "Numeric ID of the contact to get"
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Contact not found"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "jwt must be provided"
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Insufficient permission"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "email_login": {
            "type": "string"
          },
          "full_name": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "emails": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "phone": {
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          "createdAt": {
            "type": "string"
          },
          "contacts": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Contact"
            }
          }
        }
      },
      "UserResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "email_login": {
            "type": "string"
          },
          "full_name": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "emails": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "phone": {
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          "createdAt": {
            "type": "string"
          }
        }
      },
      "UserCreate": {
        "type": "object",
        "properties": {
          "email_login": {
            "type": "string"
          },
          "full_name": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "emails": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "phone": {
            "type": "array",
            "items": {
              "type": "number"
            }
          }
        }
      },
      "Contact": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "full_name": {
            "type": "string"
          },
          "emails": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "phone": {
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          "createdAt": {
            "type": "string"
          }
        }
      },
      "ContactCreate": {
        "type": "object",
        "properties": {
          "full_name": {
            "type": "string"
          },
          "emails": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "phone": {
            "type": "array",
            "items": {
              "type": "number"
            }
          }
        }
      },
      "Login": {
        "type": "object",
        "properties": {
          "email_login": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "LoginResponse": {
        "type": "object",
        "properties": {
          "token": "string",
          "user": "#/components/schemas/UserResponse"
        }
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
